apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pokedex-v2-rollout
spec:
  replicas: 100
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
      - name: pokedex
        image: pokedex:latest
  strategy:
    canary:
      steps:
      - setWeight: 1
      - pause: {}
